name: Lint YAML Files

description: A composite action for linting YAML files.

inputs:
  python-version:
    description: The version of Python to use when running `yamllint`.
    default: 3.14.2
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install yamllint
      run: |
        pip install --upgrade pip
        pip install yamllint
      shell: sh

    - name: Lint YAML Files
      run: |-
        yamllint -c "$GITHUB_ACTION_PATH/.yamllint.yml" .
      shell: sh
